### ISSUE TITLE
[Front] Bug de impossibitar sair do Perfil Atual

### ISSUE THREAD

**Issue by natanbalthazar** [dsm-cefet-rj/ti-2023-1-grupo3#25]
<h3>Desafio:</h3>

- **Eu** como usuário do sistema
- **Gostaria de** sair da minha conta
- **Por** motivos de segurança e para alterar de conta.

<h3>Problema:</h3>

1. Foi notado no sistema que, estando logado no sistema, ao clicar no botão "Sair", não era possível sair da conta.
2. Nesse caso, é importante verificar qual o porque disso para que seja corrigido e também se acontece para diferentes tipos de perfil.

![Image](https://github.com/dsm-cefet-rj/ti-2023-1-grupo3/assets/62712246/027b8c83-052e-4244-82a6-e0a0a7bb5497)

<h3>Critérios de Aceite:</h3>

1. Ao clicar no botão "Sair", ser possível sair de qualquer conta, mesmo que seja um paciente ou psicólogo.

**Comment by RicardoFAraujo** [comment]
Logout implementado e funcional.

![Image](https://github.com/dsm-cefet-rj/ti-2023-1-grupo3/assets/128547223/5f0b894a-3ea5-46e4-b7a5-e2a63d3485f8)
