### ISSUE TITLE
[PSW - Front] Crash do Json Server

### ISSUE THREAD

**Issue by PADRAOGABRIEL** [dsm-cefet-rj/ti-2023-1-grupo3#28]
<h3>Desafio:</h3>

- *Eu* como Usuário do Sistema
- *Gostaria que* o site continue funcionando corretamente após a marcação de consultas
- *Para* continuar utilizando as funcionalidades corretamente

<h3>Problema:</h3>
1. Foi notado que, em alguns profissionais, ao marcar a consulta esse problema acontece (problema apresentado nas imagens abaixo).

![Image](https://github.com/dsm-cefet-rj/ti-2023-1-grupo3/assets/95319407/c94417a6-e08e-4fde-9389-ff8e6ad1059a)

<br>

![Image](https://github.com/dsm-cefet-rj/ti-2023-1-grupo3/assets/95319407/a1ebb8a3-959b-42ca-8220-eff5a6599065)

<h3>Critérios de Aceite:</h3>

1. Aplicação funcionando corretamente após requisições no servidor

**Comment by pedrocassa** [comment]
Não estamos utilizando mais o json server
