### ISSUE TITLE
[Front] Bug ao alterar a nota de um Psicólogo

### ISSUE THREAD

**Issue by natanbalthazar** [dsm-cefet-rj/ti-2023-1-grupo3#30]
<h3>Desafio:</h3>

- **Eu** como QA
- **Gostaria que** ao modificar a nota do Psicólogo, fosse possível alterar a quantidade de estrelas preenchidas
- **Para** ter uma visão de forma correta das informações do sistema 

<h3>Problema:</h3>

1. Como forma de teste, foi alterado localmente a mudança do valor da nota de um Psicólogo.
2. Ao mudar, foi apresentado um bug que não era esperado, sendo valido testar o porque.

![Image](https://github.com/dsm-cefet-rj/ti-2023-1-grupo3/assets/62712246/bd0dd797-eb02-42a1-9c14-066f703a8337)

<h3>Critérios de Aceite:</h3>

1. As notas estarem adequadas a quantidade de estrelas apresentadas.
2. Outra forma de resolver o problema, seria apresentando a pontuação similar a do Ifood, indicando apenas uma estrela e a nota do lado:

![Image](https://github.com/dsm-cefet-rj/ti-2023-1-grupo3/assets/62712246/52256137-3b2e-476e-835c-e08457c9aee0)

**Comment by pedrocassa** [comment]
Existe essa parte de rating somente como visualização. Não existe a possibilidade de dar feedback na aplicação hoje. Acredito que não será possível implementar a tempo.
