### ISSUE TITLE
[PSW - Back-End] CRUD de Usuários

### ISSUE THREAD

**Issue by pedrocassa** [dsm-cefet-rj/ti-2023-1-grupo3#37]

**Comment by pedrocassa** [comment]
Tempo - 4h

**Comment by RicardoFAraujo** [comment]
Desafio:
**Eu**, como QA
**gostaria que** os usuários pudessem gerenciar suas informações pessoais no sistema
**para que** possam manter seus dados atualizados e corretos.

Problema:
O sistema não permite que os usuários excluam ou editem suas informações pessoais depois de cadastradas. Essa funcionalidade é importante para garantir que os usuários possam corrigir ou atualizar informações incorretas ou desatualizadas. Sem essa opção, os usuários ficam sem controle sobre as informações em seu perfil e podem ficar insatisfeitos com a experiência do usuário no sistema.
