### ISSUE TITLE
[PSW - Back-End] Autenticação e rota de login

### ISSUE THREAD

**Issue by pedrocassa** [dsm-cefet-rj/ti-2023-1-grupo3#38]

**Comment by pedrocassa** [comment]
Tempo - 1h

**Comment by RicardoFAraujo** [comment]
Autenticação e rota de login funcionais.


![Image](https://github.com/dsm-cefet-rj/ti-2023-1-grupo3/assets/128547223/c8fdf0e8-5a7d-4386-a607-ff433093f31e)


![Image](https://github.com/dsm-cefet-rj/ti-2023-1-grupo3/assets/128547223/2f0d2f3f-69e5-408c-8563-56b127567cd4)


![Image](https://github.com/dsm-cefet-rj/ti-2023-1-grupo3/assets/128547223/fbc8f654-9e63-46f2-b4e7-b04896b2d988)
