### ISSUE TITLE
[PSW - Back-End] Integrar backend na parte de profissionais

### ISSUE THREAD

**Issue by pedrocassa** [dsm-cefet-rj/ti-2023-1-grupo3#40]

**Comment by pedrocassa** [comment]
Tempo - 2h

**Comment by RicardoFAraujo** [comment]
Parte de profissionais integrada e funcional.

![Image](https://github.com/dsm-cefet-rj/ti-2023-1-grupo3/assets/128547223/600e012f-d999-4549-aae5-1c55bb498592)
