### ISSUE TITLE
[PSW - Back-End] Integrar backend na parte de usuários

### ISSUE THREAD

**Issue by pedrocassa** [dsm-cefet-rj/ti-2023-1-grupo3#41]

**Comment by pedrocassa** [comment]
Tempo - 2h

**Comment by RicardoFAraujo** [comment]
Parte de usuários integrada e funcional.


![Image](https://github.com/dsm-cefet-rj/ti-2023-1-grupo3/assets/128547223/36d77e6e-bd14-4c8c-876f-dd529c323fa1)
